# Generated by Django 4.1 on 2022-09-01 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
