# Generated by Django 4.1 on 2022-09-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_first_name_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_body',
            field=models.TextField(),
        ),
    ]
