# Generated by Django 4.1 on 2022-09-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_body',
            field=models.TextField(max_length=500),
        ),
    ]
