# Generated by Django 4.1 on 2022-08-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pfp',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
