# Generated by Django 4.1 on 2022-09-02 20:43

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=image_cropping.fields.ImageCropField(upload_to='media'),
        ),
    ]
