# Generated by Django 4.1 on 2022-09-02 20:46

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_user_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=image_cropping.fields.ImageCropField(upload_to=''),
        ),
    ]
