# Generated by Django 4.1 on 2022-09-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_user_cropping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cropping',
        ),
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.ImageField(upload_to=''),
        ),
    ]
